# Generated by Django 4.0.4 on 2022-05-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_contry_country_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_state', to='jobs.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=128),
        ),
    ]
