# Generated by Django 4.0.4 on 2022-05-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_country_country_country_name_alter_job_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated',
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
