# Generated by Django 4.0.4 on 2022-05-17 11:16

from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=30)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='applicant/prof_image')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('subject', models.CharField(max_length=128)),
                ('about', models.TextField()),
                ('skill', models.CharField(max_length=128)),
                ('sign', versatileimagefield.fields.VersatileImageField(upload_to='jobapplication/signature')),
                ('resume', models.FileField(upload_to='jobapplication/resumes')),
            ],
            options={
                'verbose_name': 'JobApplicantion',
                'verbose_name_plural': 'JobApplicantions',
            },
        ),
    ]
